openapi: '3.0.1'
info:
  description: >-
    Sample RESTful APIs
  title: Sample RESTful APIs
  version: 0.9.1
paths:
  /users:
    get:
      summary: Show a list of users.
      parameters:
        - name: name
          in: query
          description: Search by user names
          schema:
            type: string
      responses:
        '200':
          description: Successfully returns a list of users.
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/User'
    post:
      summary: Create a new user.
      requestBody:
        content:
          application/json:
            schema:
              properties:
                name:
                  type: string
                is_admin:
                  type: boolean
              required: [name]
      responses:
        '204':
          description: Successfully created a new user.
  /users/{id}:
    get:
      summary: Get an information of the specified user.
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
      responses:
        '200':
          description: Successfully returns a user.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/User'
        '404':
          description: No user found
          content:
            application/json:
              schema:
                properties:
                  error:
                    type: string
components:
  schemas:
    User:
      properties:
        id:
          type: integer
        name:
          type: string
        is_admin:
          type: boolean
