name: CI

on:
  push:
    branches: [ '*' ]
  pull_request:
    branches: [ '*' ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      with:
        path: ./apispec
    - name: Install Roswell
      env:
        LISP: ${{ matrix.lisp }}
      run: |
        curl -L https://raw.githubusercontent.com/roswell/roswell/master/scripts/install-for-ci.sh | sh
    - name: Install Rove
      run: ros install rove
    - name: Run tests
      run: |
        PATH="~/.roswell/bin:$PATH"
        mkdir -p ~/.roswell/local-projects/cxxxr
        mv $GITHUB_WORKSPACE/apispec ~/.roswell/local-projects/cxxxr/apispec
        cd ~/.roswell/local-projects/cxxxr/apispec
        rove apispec.asd
